### PR TITLE
Add io.js 0.12 support

### PR DESCRIPTION
**Pull request by kuraga**

### CODE REVIEW

**Comment by kuraga** [comment]
Doesn't work... But won't you support 0.12?

**Comment by sebmck** [comment]
0.12 is unstable Node which isn't necessary now that 0.13 is out so dunno why anyone would support it.

**Comment by fkling** [comment]
@sebmck: I think you are confusing v0.11 with v0.12 ;)

**Comment by sebmck** [comment]
@fkling Yup :/

**Comment by zpao** [comment]
We use jest for testing which doesn't work well with node > 0.10. That doesn't mean that jstransform itself won't work with node 0.12 or iojs.

Looking at the actual failure, it's doesn't seem like the issue is necessarily with jest though…

**Comment by kuraga** [comment]
Ok, then you about problem. Close

**Pull request closed without merging**
