### PR TITLE
Make class methods non-enumerable and writable

### PR DESCRIPTION
**Pull request by sebmck**
This PR makes class methods non-enumerable and writable which is inline with the spec.

[14.5.14 Runtime Semantics: ClassDefinitionEvaluation](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-runtime-semantics-classdefinitionevaluation)

> Let desc be the PropertyDescriptor{[[Value]]: F, [[Writable]]: true, [[Enumerable]]: false, [[Configurable]]: true}.

This will be a breaking change and should be done sooner rather than later.

### CODE REVIEW

**Comment by jeffmo** [comment]
Can you add an option that toggles es3/ie8 compat mode? Object.defineProperty isn’t available in IE8 (which we still need to support at FB for at least a while)

Also, looks like there are some failing tests

**Comment by sebmck** [comment]
Ah, didn't see the tests. Will do.

**Comment by sebmck** [comment]
@jeffmo Done. All the tests pass but it's stuck in a loop on Travis because jshint is erroring due to a change unrelated to this PR.

**Comment by sebmck** [comment]
Just want to reiterate that this will break code that relies on methods being enumerable. [alt](https://github.com/goatslacker/alt) did for instance until I reported it and it was fixed. It's part and parcel of adopting unstable standards.

**Comment by jeffmo** [comment]
This is great, thanks for sending this! I'll be sure we do a major version bump on our next publish

**Comment by sebmck** [comment]
@jeffmo Great! More than happy to help push future adoption and interoperability.

**Pull request merged**
