### PR TITLE
Introduce es6-object-computed-property-visitors

### PR DESCRIPTION
**Pull request by kaustubh-karkare**

### CODE REVIEW

**Comment by appsforartists** [comment]
@zpao @gabelevi @jeffmo Can we land this?

**Comment by zpao** [comment]
@kaustubh-karkare is this the same as what you landed internally already?

**Comment by zpao** [comment]
@appsforartists I doubt I'll ship a react-tools for just this (but I will kill react-tools for you, and me, and the rest of the world - see #81)... Also not awesome to turn on more transforms by default in a patch version IMO. I'll consider it, though we can have that discussion in react.

**Comment by appsforartists** [comment]
@zpao :+1: 

I am not interested in bumping react-tools for its own sake - I just want to move useful transforms like this closer to being usable in jsx-loader and node-jsx.

**Comment by kaustubh-karkare** [comment]
@zpao Yes.

**Pull request merged**
