### PR TITLE
Introduce ES6 Call Spread operator.

### PR DESCRIPTION
**Pull request by kaustubh-karkare**
Introducing new visitor which uses injection of temporary variables at start of scope to transform the call spread operator.

### CODE REVIEW

**Comment by sebmck** [comment]
This will bomb when spreading computed member expressions.

```javascript
obj['meth' + 'od'](0, 3, ...[1, 2])
```

becomes

```javascript
obj.'meth' + 'od'.apply(obj, [0, 3].concat([1, 2]))
```

**Comment by kaustubh-karkare** [comment]
> The isTemporaryVariableRequired logic will also fail if the target isn't a local variable since it could trigger a getter to be evaluated twice.

Could you provide an example to help me understand?

**Comment by sebmck** [comment]
```javascript
var obj = {
  calls: 0,
  get context() {
    this.calls++;
    return {
      add: (a, b) => a + b
    };
  }
};
var nums = [1, 2];
obj.context.add(...nums);
obj.calls === 1; // this will actually be 2
```

**Comment by DmitrySoshnikov** [comment]
We could have partial support and don't implement for getters yet, however, it seems just easier to always inject a temp variable for the base, and remove the `isTemporaryVariableRequired`.

Yes, we need to fix the computed properties cases though.

**Comment by sebmck** [comment]
Also

```javascript
max(1, 2, ...list);
```

should be

```javascript
max.apply(undefined, [1, 2].concat(list));
```

not

```javascript
max.apply(null, [1, 2].concat(list));
```

**Comment by kaustubh-karkare** [comment]
No worries: all this is really useful, and I'm learning new things.

Regarding the null/undefined thing, this is best explanation I found: http://stackoverflow.com/a/11659165/903585 , so yes, I will update.

**Comment by DmitrySoshnikov** [comment]
I think it's better to keep `null` (to avoid potential overrides of `undefined` in older browsers). From the ES5 spec perspective they are handled [equally](http://es5.github.io/#x10.4.3) in terms of promotion to the Global object (or staying the same in the strict mode).

**Comment by jeffmo** [comment]
Can you rebase this on top of #66 which was just merged?

**Comment by spicyj** [comment]
We could always do `void 0` if overwriting `undefined` is a concern?

**Comment by DmitrySoshnikov** [comment]
@spicyj why? I don't think it should be `undefined` actually, but `null`.

**Comment by spicyj** [comment]
Isn't `undefined` the default context for function calls in strict mode?

image

**Comment by DmitrySoshnikov** [comment]
It is, however, that's said, by [10.4.3](http://es5.github.io/#x10.4.3) they are treated the same, and most of the user-level code was always passing `null`, not `undefined`. And we thinking about human-readable output, it will be more predictable for users to see `null` there. But main algorithm of the base isn't a reference, yes, passes `undefined`.

**Pull request merged**
