### PR TITLE
Add option to disable ast caching

### PR DESCRIPTION
**Pull request by jcreedcmu**

### CODE REVIEW

**Comment by jcreedcmu** [comment]
Making a little LRU cache is probably super easy, yes, but happier to just have disable-cache option in its own PR.

**Comment by amasad** [comment]
any updates here?

**Comment by jcreedcmu** [comment]
Yeah, jeffmo, does this look ok now that I pushed it into the options object like you asked?

**Comment by jeffmo** [comment]
Gorgeous!

**Pull request merged**
